<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <groupId>it</groupId>
    <artifactId>it-inline</artifactId>
    <version>1.0</version>
    <build>
        <plugins>
            <plugin>
                <groupId>io.github.heyuch</groupId>
                <artifactId>ddl-codegen-maven-plugin</artifactId>
                <version>1.0-SNAPSHOT</version>
                <configuration>
                    <ddl>create table user (id bigint primary key, name varchar(50) not null comment '用户名')</ddl>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
